{{- if .Values.grpcRoute.enabled -}}
{{- $grpcPort := .Values.grpc.port -}}
{{- $name := include "grpc-service.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ include "grpc-service.fullname" . }}
  labels:
    {{- include "grpc-service.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- range .Values.grpcRoute.parentRefs }}
    - name: {{ .name }}
      kind: {{ .kind }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
    {{- end }}
  
  hostnames:
    {{- range .Values.grpcRoute.hostnames }}
    - "{{ . }}"
    {{- end }}

  rules:
    {{- range .Values.grpcRoute.rules }}
    - matches:
        {{- range .matches }}
        - method:
            {{- if .method.method }}
            method: {{ .method.method }}
            {{- end }}
            {{- if .method.service }}
            service: {{ .method.service }}
            {{- end }}
        {{- end }}
      backendRefs:
        {{- range .backendRefs }}
        - group: "{{ .group | default "" }}"
          kind: "{{ .kind }}"
          name: {{ $name }}
          port: {{ $grpcPort  }}
          weight: {{ .weight | default 1 }}
        {{- end }}
    {{- end }}
{{- end }}