apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: agenda-agendash
  namespace: kube-system
spec:
  chart: web-service
  repo: https://sachinshakya507.github.io/charts
  targetNamespace: default
  valuesContent: |-
    image:
      repository: nginx
      pullPolicy: Always
      tag: "latest"