apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nginx11
  namespace: kube-system
spec:
  chart: web-service
  repo: https://sachinshakya507.github.io/charts
  targetNamespace: chart-test
  valuesContent: |-
    replicaCount: 1
    image:
      repository: nginx
      pullPolicy: Always
      tag: "latest"
    httpRoute:
      enabled: true
      hostnames:
        - "envoytest1.hamropatro.com"
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
    service:
      type: ClusterIP
      port: 80

    securityContext: 
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000