apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nginx11
  namespace: kube-system
spec:
  chart: web-service
  repo: https://sachinshakya507.github.io/charts
  targetNamespace: default
  valuesContent: |-
    replicaCount: 1
    image:
      repository: nginx
      pullPolicy: Always
      tag: "latest"
    httpRoute:
      enabled: true
      hostnames:
        - "envoytest11.hamropatro.com"
      rules:
        - backendRefs:
          - group: ""
            kind: Service
            weight: 1
            name: nginx11-web-service
          matches:
            - path:
                type: PathPrefix
                value: /
    service:
      type: ClusterIP
      port: 80

    securityContext: 
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000