apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grpc
  namespace: kube-system
spec:
  chart: web-service
  repo: https://sachinshakya507.github.io/charts
  targetNamespace: chart-test
  valuesContent: |-
    replicaCount: 1
    image: 
      repository: ghcr.io/projectcontour/yages
      tag: "v0.1.0"
      pullPolicy: Always

    grpcRoute:
      enabled: true
      hostnames:
        - "grpc-envoy1.hamropatro.com"
      rules:
      - matches:
        - method:
            method: ServerReflectionInfo
            service: grpc.reflection.v1alpha.ServerReflection
        - method:
            method: Ping
        backendRefs:
          - group: ""
            kind: Service
            name: grpc-web-service
            port: 9000
            weight: 1
            
      service:
        type: ClusterIP
        port: 9000