apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: test-web
  namespace: kube-system
spec:
  chart: web-service
  repo: https://sachinshakya507.github.io/charts
  targetNamespace: default
  valuesContent: |-
    replicaCount: 1
    image:
      repository: docker.io/hamropatrorepo/election-update
      pullPolicy: IfNotPresent
      tag: "v1"
    
    imagePullSecrets:
      - name: regcred
    
    liveness:
      path: /
    readiness:
      path: /

    service:
      targetPort: 80

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi

    httpRoute:
      enabled: true
      hostnames:
        - "test-deploy1.hamrostack.com"
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - group: ""
              kind: "Service"
              weight: 1
              name: ""
              port: ""