on:
  push:
    branches: [ gh-pages ]
  # Enables manual trigger from Actions tab
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Copy files
        run: |
          # Create destination directory if it doesn't exist
          mkdir -p build
          
          # Copy files from source to destination
          cp -r index.yaml build/

      
      # Optional: If you want to commit the changes back to the repository
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add build
          git commit -m "Copy files from source to destination" || echo "No changes to commit"
          git push