name: Release Charts
on:
  push:
    branches:
      - main

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
            charts_dir: helm
            # pages_branch: main #change th branch
            # config: helm/cr.yaml 
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # CR_SKIP_EXISTING: true
          # CR_INDEX_PATH: "build/index.yaml"
    move_file:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        with:
            fetch-depth: 0  # Fetch all history and branches
            ref: gh-pages
        - name: Move Updated File
          run: |
            cp index.yaml build/index.yaml
  
        # Configure Git to push changes back
        - name: Configure Git
          run: |
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
  
        # Commit and push the moved file
        - name: Commit and Push Changes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            git add build/index.yaml
            git commit -m "copy file"
            git push