{{- if .Values.httpRoute.enabled -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "web-service.fullname" . }}
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- range .Values.httpRoute.parentRefs }}
    - name: {{ .name }}
      kind: {{ .kind }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
    {{- end }}

  hostnames:
    {{- range .Values.httpRoute.hostnames }}
    - "{{ . }}"
    {{- end }}

  rules:
    {{- range .Values.httpRoute.rules }}
    - backendRefs:
        {{- range .backendRefs }}
        - group: "{{ .group | default "" }}"  # Use default "" if group is missing
          kind: "{{ .kind }}"
          name: "{{ include "web-service.fullname" . }}"
          port: {{ $svcPort }} 
          weight: {{ .weight | default 1 }}  # Use default weight 1 if missing
        {{- end }}
      matches:
        {{- range .matches }}
        - path:
            type: {{ .path.type }}
            value: {{ .path.value }}
        {{- end }}
    {{- end }}
{{- end }}