{{- if .Values.httpRoute.enabled -}}
{{- $svcPort := .Values.service.port -}}
{{- $name := include "web-service.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $name }}
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- range .Values.httpRoute.parentRefs }}
    - name: {{ .name }}
      kind: {{ .kind }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
    {{- end }}

  hostnames:
    {{- range .Values.httpRoute.hostnames }}
    - "{{ . }}"
    {{- end }}

  rules:
    {{- range .Values.httpRoute.rules }}
    - backendRefs:
        {{- range .backendRefs }}
        - group: {{ .group }}
          kind: {{ .kind }}
          weight: {{ .weight }}
          name: {{ $name }}
          port: {{ $svcPort }}
        {{- end }}
      matches:
        {{- range .matches }}
        - path:
            type: {{ .path.type }}
            value: {{ .path.value }}
        {{- end }}
    {{- end }}
{{- end }}