apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: {{ include "web-service.fullname" . }}
  namespace: {{ .Values.httpRoute.namespace }}
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- range .Values.httpRoute.parentRefs }}
    - name: {{ .name }}
      kind: {{ .kind }}
      namespace: {{ .namespace | default "default" }}
    {{- end }}
  
  hostnames:
    {{- range .Values.httpRoute.hostnames }}
    - "{{ . }}"
    {{- end }}
  
  rules:
    - backendRefs:
        - group: {{ .Values.httpRoute.rules.backendRefs.group }}
          kind: {{ .Values.httpRoute.rules.backendRefs.kind }}
          name: {{ .Values.httpRoute.rules.backendRefs.name }}
          port: {{ .Values.httpRoute.rules.backendRefs.port }}
          weight: {{ .Values.httpRoute.rules.backendRefs.weight }}
      matches:
        - path:
            type: {{ .Values.httpRoute.rules.matches.type }}
            value: {{ .Values.httpRoute.rules.matches.value }}
